### ISSUE TITLE
Unable to download past 2-3 episodes

### ISSUE THREAD

**Issue by ElectroZephyr** [yasoob/watchcartoononline-dl#13]
I tried downloading Iron man Armored Adventures and couldn't make it past two or three episodes. I tried 2.7, 2.4 and 3.6 but still couldnt get anything besides a couple episodes. I get the following error's from Command Prompt on 2.7
I'd love for this to work because i'm trying to fill up my Plex server with some of my favorite series.

Traceback (most recent call last):
  File "watch-dl.py", line 168, in <module>
    episodes_extractor(sys.argv[1])
  File "watch-dl.py", line 77, in episodes_extractor
    doAnEpisode(url)
  File "watch-dl.py", line 160, in doAnEpisode
    downloader(final_url, name)
  File "watch-dl.py", line 84, in downloader
    u = urllib2.urlopen(fileurl)
  File "C:\Python27amd64\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27amd64\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27amd64\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27amd64\lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "C:\Python27amd64\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27amd64\lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27amd64\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27amd64\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27amd64\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27amd64\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27amd64\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Or This: 

Traceback (most recent call last):
  File "watch-dl.py", line 168, in <module>
    episodes_extractor(sys.argv[1])
  File "watch-dl.py", line 77, in episodes_extractor
    doAnEpisode(url)
  File "watch-dl.py", line 160, in doAnEpisode
    downloader(final_url, name)
  File "watch-dl.py", line 84, in downloader
    u = urllib2.urlopen(fileurl)
  File "C:\Python27amd64\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27amd64\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27amd64\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27amd64\lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "C:\Python27amd64\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27amd64\lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27amd64\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27amd64\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27amd64\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27amd64\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27amd64\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by yasoob** [comment]
should be resolved now :)
