### ISSUE TITLE
Wrong description + regex Broken?

### ISSUE THREAD

**Issue by moorer2k** [yasoob/watchcartoononline-dl#20]
You say it's for watchcartoononline.com but all the source points @ watchcartoononline.io ? Maybe you missed that, figured i'd let you know :) Thanks for this.

Also, getting an error now, using this command line:

> `py watch-dl.py https://www.watchcartoononline.io/anime/naruto-shippuden -r 371 416 -d naruto`

[watchcartoononline-dl] Downloading webpage
[watchcartoononline-dl] Finding video
Traceback (most recent call last):
  File "watch-dl.py", line 218, in <module>
    episodes_extractor(url, ep_range, dir)
  File "watch-dl.py", line 106, in episodes_extractor
    doAnEpisode(url, directory)
  File "watch-dl.py", line 189, in doAnEpisode
    final_url = info_extractor(url)
  File "watch-dl.py", line 34, in info_extractor
    video_url = re.search(b'<iframe [^>]*src="https://www.watchcartoononline.io/inc/(.+?)>', webpage).group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by zang74** [comment]
It would appear that WCO has changed their layout somewhat, and the “video_url = re.search…” line is not finding the REGEX match it’s looking for. They’ve begun—I won’t say encrypting—but obfuscating the URL to the actual file using JavaScript. This has likely been done because many of the lesser cartoon sites seem to scrape others for content. 

I’d help out on this git myself, but it’s beyond my JavaScript knowledge.

**Comment by L33T-H4X0R-D00D** [comment]
I get errors no matter if I use the .com or .io addresses. 

>python.exe "C:\Users\Admin\Downloads\watchcartoononline-dl-master\watch-dl.py" "https://www.watchcartoononline.com/anime/ren-stimpy-adult-party-cartoon"

Result: {'url': ['https://www.watchcartoononline.com/anime/ren-stimpy-adult-party-cartoon'], 'directory': None, 'range': None}
[watchcartoononline-dl] looks like a list of episodes (season?), extracting episode page URLs...
ERROR: URL was invalid, please use a valid URL from www.watchcartoononline.com


>python.exe "C:\Users\Admin\Downloads\watchcartoononline-dl-master\watch-dl.py" "https://www.watchcartoononline.io/anime/ren-stimpy-adult-party-cartoon"

Result: {'url': ['https://www.watchcartoononline.io/anime/ren-stimpy-adult-party-cartoon'], 'directory': None, 'range': None}
[watchcartoononline-dl] looks like a list of episodes (season?), extracting episode page URLs...
[watchcartoononline-dl]  Downloading webpage
[watchcartoononline-dl]  Finding episode(s)
URLs found:
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-1-onward-and-upward
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-2-ren-seeks-help
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-3-fire-dogs-2
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-4-naked-beach-frenzy
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-5-altruists
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-6-stimpys-pregnant
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-1-onward-and-upward
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-2-ren-seeks-help
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-3-fire-dogs-2
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-4-naked-beach-frenzy
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-5-altruists
https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-6-stimpys-pregnant
[watchcartoononline-dl]  Downloading https://www.watchcartoononline.io/ren-stimpy-adult-party-cartoon-episode-1-onward-and-upward
[watchcartoononline-dl] Downloading webpage
[watchcartoononline-dl] Finding video
Traceback (most recent call last):
  File "C:\Users\Adam\Downloads\watchcartoononline-dl-master\watch-dl.py", line 218, in <module>
    episodes_extractor(url, ep_range, dir)
  File "C:\Users\Adam\Downloads\watchcartoononline-dl-master\watch-dl.py", line 106, in episodes_extractor
    doAnEpisode(url, directory)
  File "C:\Users\Adam\Downloads\watchcartoononline-dl-master\watch-dl.py", line 189, in doAnEpisode
    final_url = info_extractor(url)
  File "C:\Users\Adam\Downloads\watchcartoononline-dl-master\watch-dl.py", line 34, in info_extractor
    video_url = re.search(b'<iframe [^>]*src="https://www.watchcartoononline.io/inc/(.+?)>', webpage).group()
AttributeError: 'NoneType' object has no attribute 'group'

This tool worked great for months. Seems like it's been broken for a while now.
